### ISSUE TITLE
Make getters work with immutable Data

### ISSUE THREAD

**Issue by mlr-msft** [dzamlo/rust-bitfield#23]
I'd like to be able to work with immutable data. e.g.:

```
impl<T> IpV4Header<T> {
    pub fn validate<T>(bytes: T) -> Result<()>
    where
        T: AsRef<[u8]>,
    { ...
```

Unfortunately, the accessor functions (e.g. `get_protocol`) that are generated require the `AsMut<[u8]>` trait. Is there something I'm not doing correctly?

Thanks in advance.

**Comment by dzamlo** [comment]
Ti use the getter and setter require that the type implement `BitRange` (and `Bit` for single bit field). And the implementation only exist for `T: AsMut<[$slice_ty]> + AsRef<[$slice_ty]` at the moment.

So yes, currently the getter will also require `AsMut<[u8]>`.

Maybe, I should split the `BitRange` trait in two (Only with a getter and one with a setter). And only require the necessary one of the two for each method.
