### ISSUE TITLE
Feature Request: Derive Bitwise Operators

### ISSUE THREAD

**Issue by PokeJofeJr4th** [dzamlo/rust-bitfield#43]
Any time I've used a bitfield, I've done bitwise operations on it. Due to the positional nature, shifting shouldn't be included, but I think it would be nice to have ways to generate impls for `BitAnd`, `BitOr`, and `BitXor`. I believe I can make this pretty quickly; I want to gauge if users and maintainers like this idea first.

I propose a syntax like is used for debug:
```rs
bitfield!{
   pub struct BitField1(u16);
   impl Debug;
   impl BitAnd;
   impl BitOr;
   u8;
   field1, set_field1: 10, 0;
   pub field2, _ : 12, 3;
}
```

**Comment by dzamlo** [comment]
I've never needed that, but the cost to add it seems low, so I would be ok to add it if you found that useful.

Regarding the syntax, that seems good to me.

**Comment by PokeJofeJr4th** [comment]
Completed as of 0.16.0
