### ISSUE TITLE
bitfield 0.16.2 is incompatible with bitfield 0.16.1

### ISSUE THREAD

**Issue by xobs** [dzamlo/rust-bitfield#50]
When trying to build the latest `probe-rs` without a lockfile (such as when it's built as a library), a large number of errors are generated. This is because it specifies a dependency of `bitfield = "0.16"`.

The project includes a `Cargo.lock` that pins this version to `0.16.1`. However, when building without a lockfile, it will instead pick up `0.16.2`, which is not compatible.

The workaround is to pin the version to `bitfield = "=0.16.1"`.

Is it possible to fix this by pushing a newer version that keeps compatibility with the previous API?

**Comment by dzamlo** [comment]
I have yanked the version, this should solve the issue. Can you confirm ?

Sorry for the issue.

**Comment by xobs** [comment]
I can verify that it now picks up the previous version. Thanks for the quick fix!
